# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/technical-blog',
                'doc_host': 'https://Matthew-Redrup.github.io',
                'git_url': 'https://github.com/Matthew-Redrup/technical-blog',
                'lib_path': 'technical_blog'},
  'syms': {'technical_blog.core': {'technical_blog.core.foo': ('core.html#foo', 'technical_blog/core.py')}}}
