# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/technical-blog',
                'doc_host': 'https://Matthew-Redrup.github.io',
                'git_url': 'https://github.com/Matthew-Redrup/technical-blog',
                'lib_path': 'technical_blog'},
  'syms': { 'technical_blog.blog_components': { 'technical_blog.blog_components.code_block': ( 'blog_components.html#code_block',
                                                                                               'technical_blog/blog_components.py'),
                                                'technical_blog.blog_components.create_nav': ( 'blog_components.html#create_nav',
                                                                                               'technical_blog/blog_components.py'),
                                                'technical_blog.blog_components.math_block': ( 'blog_components.html#math_block',
                                                                                               'technical_blog/blog_components.py'),
                                                'technical_blog.blog_components.topic_card': ( 'blog_components.html#topic_card',
                                                                                               'technical_blog/blog_components.py')},
            'technical_blog.core': { 'technical_blog.core.get_nb_url': ('core.html#get_nb_url', 'technical_blog/core.py'),
                                     'technical_blog.core.read_meta': ('core.html#read_meta', 'technical_blog/core.py'),
                                     'technical_blog.core.slugify': ('core.html#slugify', 'technical_blog/core.py')}}}
