"""Reusable components for the technical blog"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_blog_components.ipynb.

# %% auto 0
__all__ = ['create_navigation', 'topic_card', 'math_block']

# %% ../nbs/01_blog_components.ipynb 3
from fasthtml.common import *
from typing import List, Dict, Any

# %% ../nbs/01_blog_components.ipynb 5
def create_navigation(current_topic: str = None) -> Div:
    """Create the main navigation bar for the blog"""
    nav_items = [
        ('Home', '/'),
        ('RBE Series', '/rbe/'),
        ('Future Topics', '/topics/'),
        ('About', '/about/')
    ]
    
    nav_links = []
    for title, url in nav_items:
        active_class = "active" if current_topic and title.lower().startswith(current_topic.lower()) else ""
        nav_links.append(
            A(title, href=url, cls=f"nav-link {active_class}")
        )
    
    return Nav(*nav_links, cls="main-navigation")

# %% ../nbs/01_blog_components.ipynb 7
def topic_card(title: str, description: str, url: str, status: str = "available") -> Div:
    """Create a card for a blog topic"""
    status_class = f"topic-{status}"
    
    return Div(
        H3(title),
        P(description),
        A("Read More →", href=url, cls="topic-link") if status == "available" else Span("Coming Soon", cls="coming-soon"),
        cls=f"topic-card {status_class}"
    )

# %% ../nbs/01_blog_components.ipynb 9
def math_block(latex: str, block: bool = True) -> Div:
    """Render LaTeX mathematics using MathJax"""
    delimiter = "$$" if block else "$"
    return Div(
        f"{delimiter}{latex}{delimiter}",
        cls="math-block" if block else "math-inline"
    )
