"""Main imports and convenience functions for Recursive Bayesian Estimation"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/rbe/00_rbe.ipynb.

# %% auto 0
__all__ = ['prob_normalize', 'prob_sample', 'prob_entropy', 'prob_kl_div', 'bayes_update', 'bayes_sequential',
           'bayes_posterior_predictive', 'pf_init', 'pf_predict', 'pf_update', 'pf_resample', 'pf_step',
           'pf_effective_size', 'rbe_estimator', 'rbe_adaptive', 'rbe_metrics', 'viz_particles', 'viz_beliefs',
           'viz_comparison', 'viz_rbe_summary']

# %% ../nbs/rbe/00_rbe.ipynb 3
# Re-export everything from submodules for convenience
from .rbe.probability import *
from .rbe.bayes_core import *
from .rbe.particle_filter import *
from .rbe.estimator import *
from .rbe.viz import *

# %% ../nbs/rbe/00_rbe.ipynb 9
# Aliases for backward compatibility
prob_normalize = normalize
prob_sample = sample
prob_entropy = entropy
prob_kl_div = kl_div
bayes_update = update
bayes_sequential = sequential
bayes_posterior_predictive = predictive
pf_init = init
pf_predict = predict
pf_update = update
pf_resample = resample
pf_step = step
pf_effective_size = eff_size
rbe_estimator = estimate
rbe_adaptive = adaptive
rbe_metrics = metrics
viz_particles = particles
viz_beliefs = beliefs
viz_comparison = comparison
viz_rbe_summary = summary

# %% ../nbs/rbe/00_rbe.ipynb 11
__all__ = [
    # Modern names (from submodules)
    'normalize', 'sample', 'entropy', 'kl_div', 'js_div', 'eff_size',
    'categorical', 'uniform', 'from_counts',
    'update', 'sequential', 'predictive', 'bayes_factor', 'interpret_bf',
    'beta_binomial_update', 'normal_normal_update',
    'init', 'predict', 'update', 'resample', 'step', 'run', 'auxiliary_pf_step',
    'estimate', 'adaptive', 'multi_model', 'metrics', 'compare_online_batch',
    'set_style', 'particles', 'beliefs', 'comparison', 'summary',
    'animate_particles', 'uncertainty_bands',
    
    # Legacy names (for backward compatibility)
    'prob_normalize', 'prob_sample', 'prob_entropy', 'prob_kl_div',
    'bayes_update', 'bayes_sequential', 'bayes_posterior_predictive',
    'pf_init', 'pf_predict', 'pf_update', 'pf_resample', 'pf_step', 'pf_effective_size',
    'rbe_estimator', 'rbe_adaptive', 'rbe_metrics',
    'viz_particles', 'viz_beliefs', 'viz_comparison', 'viz_rbe_summary'
]
